version: "3"
services: 
  database:
    container_name: MySQL
    build:
      context: ./database
      dockerfile: Dockerfile.mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin:5.2.1
    platform: linux/amd64
    ports:
      - "8080:80"
    networks:
      - mynetwork
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    
  server:
    container_name: Backend
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    expose:
      - "3000"  
    networks:
      - mynetwork

  nginx:
    container_name: Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - server

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data: